version: '3.8'

services:
  web:
    build: ./
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - migration

  migration:
    build: ./ 
    command: python3 manage.py migrate 
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env

  db:
    image: postgres:15-alpine 
    volumes:
      - ./pg_data:/var/lib/postgresql/data 
    profiles:
      - dev
    env_file:
      - ./.env

