version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --log-level debug
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - migration

  migration:
    build: ./app
    command: python3 manage.py migrate
    volumes:
      - ./app:/usr/src/app/
    env_file:
      - ./.env

