version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn app.core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.prod
    profiles:
      - web
    depends_on:
      - migration

  migration:
    build: ./app
    command: python3 manage.py migrate
    volumes:
      - ./app:/usr/src/app/
    profiles:
      - web
    env_file:
      - ./app/.env

  db:
    image: postgres:15-alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    profiles:
      - db
    env_file:
      - ./.env.db

